project-includes = ["karam_finance", "tools"]
disable-project-excludes-heuristics = true
project-excludes = [
  "**/__pycache__",
  "**/.*/**",
  "node_modules",
  "karam_finance/public/dist",
]
search-path = [
  ".",
  "../frappe",
  "../erpnext",
  "karam_finance/karam_general/report/bank_reconciliation_statement_(karam)",
  "karam_finance/karam_general/report/general_ledger_(karam)",
  "karam_finance/karam_general/report/profit_and_loss_statement_by_cost_center",
  "karam_finance/karam_general/report/trial_balance_(karam)",
  "karam_finance/karam_general/report/trial_balance_for_party_(karam)",
  "karam_finance/reporting_currency/report/general_ledger_(reporting)",
  "karam_finance/reporting_currency/report/trial_balance_for_party_(reporting)",
]
python-version = "3.14"
python-platform = "linux"
use-ignore-files = true
disable-search-path-heuristics = true
replace-imports-with-any = []
ignore-missing-imports = []
ignore-errors-in-generated-code = false
preset = "default"
baseline = "pyrefly-baseline.json"
min-severity = "warn"
check-unannotated-defs = true
infer-return-types = "checked"
infer-with-first-use = true
permissive-ignores = false

[errors]
unused-ignore = true
